name: CI/CD Automated Deploy via Local Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, local-vm]
    
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Deploying application via Docker Compose
      run: |
        # မင်းရဲ့ project folder ဆီ အရင်သွားရပါမယ်
        cd ~/mini-pos-system
        
        echo "==== Rebuilding and Restarting Containers ===="
        sudo docker compose up -d --build
        
        echo "==== Cleaning up unused old Docker images ===="
        sudo docker image prune -f